[workspace]
members = ["quad", "quad-py"]

[workspace.package]
categories = ["science"]
edition = "2021"
keywords = ["high-energy-physics", "physics"]
license = "GPL-3.0-or-later"
repository = "https://github.com/AleCandido/quad"
version = "0.1.2"
