/* automatically generated by rust-bindgen */

extern "C" {
    pub fn hello() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn modify_double(a: *mut f64);
}
extern "C" {
    pub fn rescale_error(err: f64, result_abs: f64, result_asc: f64) -> f64;
}
extern "C" {
    pub fn gsl_integration_qk(
        n: ::std::os::raw::c_int,
        a: f64,
        b: f64,
        result: *mut f64,
        abserr: *mut f64,
        resabs: *mut f64,
        resasc: *mut f64,
    );
}
extern "C" {
    pub fn looop();
}
