[package]
name = "test_vs_rgsl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
GSL = "6.0.0"
cblas = "0.4.0"