name: Benchmarks

on:
  push:
    branches: [asv_bench]
  pull_request:
    branches: [asv_bench]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          default: true
          toolchain: 1.65.0
          components: llvm-tools-preview

      - name: Quick check
        run: |
          cargo check

      - name: Run tests
        run: |
          cargo bench
