name: Python bindings

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: PyO3/maturin-action@v1
        with:
          args: --out dist

      - name: Install built wheel
        run: |
          pip install quad --no-index --find-links dist --force-reinstall

      - name: Test
        run: |
          cd quad-py
          pytest
